version: "3.9"

services:

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concrete
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  app:
    build: .
    container_name: app
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: concrete
      DB_USER: user
      DB_PASSWORD: password
    restart: always

volumes:
  postgres_data: