name: Concrete Calculator Tests

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - main

jobs:

  tests:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: concrete-calculator

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest -m "not integration" -v